---
title: "Organisation"
---

HYLA a été créée en janvier 2026. Elle est actuellement composée d'une équipe de bénévoles, et tendra à développer son activité avec une équipe salariée au cours de l'année 2026. 

# Équipe

## Conseil d'administration
### Bureau
- Laurent Godé, Président
- Alain Morand, Vice-président
- Louise Silva-Lassalle, Secrétaire
- Mariana Miranda d'Assunção, Trésorière

### Autres membres du Conseil
- Jean-Baptiste Lusson
- Emmanuel Moitry
- Francis Muller
- Myriam Poullard
- Stéphane Vitzthum

## Salariés
- Jean-Pierre Vacher, Responsable scientifique depuis mai 2026.

# Statuts
Les statuts de HYLA sont disponibles au format pdf sur [ce lien](/download/statuts_signes_tribunal_light.pdf)

# Adhésion
L’adhésion à HYLA est fixée à 10 €, et valable jusqu’au 31 décembre de l’année de son règlement.

Adhérez à HYLA en ligne via [HelloAsso](https://www.helloasso.com/associations/hyla/adhesions/bulletin-d-adhesion){.external target="_blank"}

# Contact
Adresse email de contact : hyla.asso(at)gmail.com
