---
title: "Actualités"
---

## News du 6 septembre 2026 : Liste rouge Amphibiens et Reptiles de France métropolitaine
Le Comité français de l'UICN vient de publier la mise à jour 2026 de la Liste rouge des Amphibiens et Reptiles menacés de France. À retrouver dans le lien ci-dessous.
[Liste rouge Amphibiens et Reptiles de France 2026](https://uicn.fr/liste-rouge-reptiles-amphibiens-2026/)

Points importants pour la Lorraine :

- Pélobate brun : En danger
- Crapaud vert (population continentale) : Vulnérable
- Sonneur à ventre jaune : Vulnérable
- Grenouille rousse : Quasi menacée
- Lézard des souches : Quasi menacé
- Lézard vivipare : Quasi menacé
- Vipère aspic : Quasi menacée

Pour l'Alsace, Grenouille des champs : En danger

Pour la Champagne-Ardenne, Vipère péliade : Vulnérable

## News du 22 juillet 2026 : Plus de 9000 espèces d'amphibiens dans le monde
La barre des 9000 espèces d'amphibiens décrites dans le monde a été franchie en 2026. Un article annonçant la nouvelle a été pubié dans FROGLOG de juin 2026, disponible en accès libre [sur ce lien](https://www.researchgate.net/publication/400314892_Amphibians_reach_9000_described_species_a_summary_of_ongoing_trends_challenges_and_opportunities). En juillet 2026, on compte 9081 espèces d'amphibiens, dont 8003 Anoures, 844 Urodèles et 234 Gymnophiones (source [Amphibian species of the World](https://amphibiansoftheworld.amnh.org/) au 22 juillet 2026). Et ce nombre est sous-estimé ! Il reste encore beaucoup d'espèces à décrire, notamment en Amazonie, à Madagascar et en Papouasie, un travail titanesque qui attend les systématiciens et taxinomistes pour ces prochaines décennies. L'Europe n'est pas en reste car plusieurs espèces ont été décrites ces dernières années, et plusieurs lignées évolutives méritent plus d'investigations pour déterminer leur statut.

## News du 21 juillet 2026 : *Batrachochytrium salamandrivorans* en Europe : quelle stratégie appliquer ?
Un article paru ce mois-ci dans la revue scientifique *Emerging Infectious Diseases* traite de la prise en compte des zoonoses qui touchent les populations naturelles, en s'appuyant sur l'exemple du chytride *Batrachochytrium salamandrivorans* (Bsal). Cet agent pathogène endémique des amphibiens est particulièrement impactant pour les urodèles sauvages en Europe, et a notamment mené à classer la Salamandre tachetée dans la catégorie VU de la Liste rouge mondiale de l'UICN. L'article expose l'historique de l'apparition de Bsal en Europe et rappelle l'effondrement des populations de salamandre qu'il a causé aux Pays-Bas, au nord-ouest de l'Allemagne et en Belgique. Les auteurs pointent la nécessité d'une coopération entre états pour atténuer les impacts, notamment en développant des outils de détection précoce, et de limitation de la dispersion du pathogène. Étant donné que la Lorraine est à la croisée de frontières, notamment proche de la Belgique où Bsal est documenté, cet article est particulièrement important pour nous afin de s'insérer dans une dynamique de prévention, de développer et mettre en place des mesures pour éviter l'apparition de Bsal, ou au pire de limiter sa propagation au sein des populations de tritons et de salamandres dans notre région.
L'article est disponible en libre accès à cette adresse : [https://wwwnc.cdc.gov/eid/article/32/7/25-1271_article](https://wwwnc.cdc.gov/eid/article/32/7/25-1271_article)


## News du 17 juillet 2026 : Nouveau président à BUFO
Nos voisins alsaciens de BUFO on renouvellé leur CA lors de la dernière AG de juin 2026, et Frédéric Petitpretz succède à Vincent Noël au poste de Président. 
[https://www.bufo-alsace.org/vie-associative/changement-de-presidence/](https://www.bufo-alsace.org/vie-associative/changement-de-presidence/)


## News du 3 juin 2026 : Un nouvel amphibien découvert en Lorraine !
Un nouveau taxon d'amphibien a été découvert en Lorraine grâce à l'ADN environnemental, il s'agit de la Grenouille verte des Balkans, *Pelophylax ridibundus kurtmuelleri*. Un article décrivant cette découverte a été publié dans le Bulletin de la Société d'Histoire naturelle et d'Ethnographie de Colmar, en accès public [sur le lien suivant](https://www.museumcolmar.org/bulletin/decouverte-dun-nouveau-taxon-damphibien-grace-a-ladn-environnemental-premiere-mention){.external target="_blank"}
